spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          username: MarcinCzekaj00
          password: ####################
          uri: https://github.com/MarcinCzekaj00/environment-variable.git

server:
  port: ${port:8888}

